#include <stdio.h>
#include <stdlib.h>
#include "../../testlibs/testlib.h"

unsigned char *math_sin_256_test1();
unsigned char *math_sin_256_test2();
unsigned char *math_sin_256_test3();


struct _test TESTS[] = {
    {.testId = 1, .test_function = math_sin_256_test1, .nbitplanes=1, .nrows=1024, .nbyterow=2,.title = "sin word full table autogenerated 1024 words", .verbose=0},
    {.testId = 2, .test_function = math_sin_256_test2, .nbitplanes=1, .nrows=2048+512, .nbyterow=2,.title = "sin/cos word full table autogenerated 1024 words", .verbose=0},
    {.testId = 3, .test_function = math_sin_256_test3, .nbitplanes=1, .nrows=1024, .nbyterow=2,.title = "cos word full table autogenerated 1024 words", .verbose=0},

    {.testId = 0, .test_function = NULL}
};

TEST_FUNC_IMPLEMENTATION(TESTS,"math_sin_256.test")
